# Generated by Django 3.0.5 on 2020-05-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_auto_20200531_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableingredient',
            options={'ordering': ('-modified', '-created', '-expire_date')},
        ),
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ('-modified', '-created')},
        ),
    ]
